name: docker

on:
  workflow_run:
    workflows: ["golangci-lint"]
    types:
      - completed

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: generate tags
        id: gen_tags
        run: |
          if [[ $GITHUB_REF == 'refs/tags/'* ]]; then
            TAGS="tphoney/plex-lookup:latest,tphoney/plex-lookup:'${GITHUB_REF/refs\/tags\//}'"
          else
            TAGS="tphoney/plex-lookup:latest"
          fi
          echo "$GITHUB_REF using: $TAGS"
          echo "TAGS=$TAGS" >> "$GITHUB_ENV"
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ TAGS }} 
